---
- name: Uninstall GlusterFS
  hosts: oo_first_master
  tasks:
  - name: Run glusterfs uninstall role for S3 resources
    include_role:
      name: openshift_storage_glusterfs
      tasks_from: uninstall_s3.yml
