---
# Check image version mentioned in the inventory:
# Fail in case:
#    - If the version mentioned is equal to the running version
#    - If the version mentioned is less than the running version
# Assumption:
#    - all the versions mentioned of the format v3.x and equal
- name: Get GlusterFS DaemonSet config
  oc_obj:
    namespace: "{{ glusterfs_namespace }}"
    kind: daemonset
    name: glusterfs-{{ glusterfs_name }}
    state: list
  register: glusterfs_ds

- name: Set glusterfs image version
  vars:
    glusterfs_image: "{{ glusterfs_ds.module_results.results[0].spec.template.spec.containers[0].image }}"
    glusterfs_run_version: "{{ glusterfs_image || regex_replace('^.*rhgs-server-rhel7:(v?)(?P<version>.*$)', '\\g<version>')) }}"
  when: glusterfs_ds.module_results.results[0]
  debug:
    msg: "glusterfs_image: '{{ glusterfs_image}}' "
  debug:
    msg: "glusterfs_run_version: '{{ glusterfs_run_version }}' "
  

    #- name: Check for specified container versions
    #  fail:
    #    msg: |
    #      A valid version tag must be specified for all GlusterFS container images.
    #      Valid image tags take the form of "v3.x" where "x" can be a one or two release
    #      versions (e.g. "v3.0" or "v3.0.1"). The following image versions were detected:
    #
    #      {% if glusterfs_is_native | bool %}GlusterFS: {{ glusterfs_version }}{% endif %}
    #
    #      {% if glusterfs_heketi_is_native | bool %}Heketi: {{ heketi_version }}{% endif %}
    #
    #      {% if glusterfs_block_deploy | bool %}glusterblock-provisioner: {{ glusterblock_version }}{% endif %}
    #  vars:
    #    glusterfs_fail: "{{ glusterfs_is_native | bool and glusterfs_version in [ ':latest', '' ] }}"
    #  when:
    #  - openshift_deployment_type == 'openshift-enterprise'
    #  - glusterfs_fail
